// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

public enum gazebo_msgs {
    public static let all: [String: Message.Type] = [
        "ContactState": ContactState.self,
		"ContactsState": ContactsState.self,
		"LinkState": LinkState.self,
		"LinkStates": LinkStates.self,
		"ModelState": ModelState.self,
		"ModelStates": ModelStates.self,
		"ODEJointProperties": ODEJointProperties.self,
		"ODEPhysics": ODEPhysics.self,
		"PerformanceMetrics": PerformanceMetrics.self,
		"SensorPerformanceMetric": SensorPerformanceMetric.self,
		"WorldState": WorldState.self]
}