// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension gazebo_msgs {

	public struct PerformanceMetrics: MessageWithHeader {
		public static let md5sum: String = "884f71fd5037b886ec5e126b83c4425a"
		public static let datatype = "gazebo_msgs/PerformanceMetrics"
		public static let definition = """
			Header header
			float64 real_time_factor
			gazebo_msgs/SensorPerformanceMetric[] sensors
			"""

		public var header: std_msgs.Header
		public var real_time_factor: Float64
		public var sensors: [SensorPerformanceMetric]

		public init(header: std_msgs.Header, real_time_factor: Float64, sensors: [SensorPerformanceMetric]) {
			self.header = header
			self.real_time_factor = real_time_factor
			self.sensors = sensors
		}

		public init() {
			header = std_msgs.Header()
			real_time_factor = Float64()
			sensors = [SensorPerformanceMetric]()
		}
	}
}