// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension gazebo_msgs {

	public struct SensorPerformanceMetric: Message {
		public static let md5sum: String = "01762ded18cfe9ebc7c8222667c99547"
		public static let datatype = "gazebo_msgs/SensorPerformanceMetric"
		public static let definition = """
			string name
			float64 sim_update_rate
			float64 real_update_rate
			float64 fps
			"""

		public var name: String
		public var sim_update_rate: Float64
		public var real_update_rate: Float64
		public var fps: Float64

		public init(name: String, sim_update_rate: Float64, real_update_rate: Float64, fps: Float64) {
			self.name = name
			self.sim_update_rate = sim_update_rate
			self.real_update_rate = real_update_rate
			self.fps = fps
		}

		public init() {
			name = String()
			sim_update_rate = Float64()
			real_update_rate = Float64()
			fps = Float64()
		}
	}
}