// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

public enum nav_msgs {
    public static let all: [String: Message.Type] = [
        "GridCells": GridCells.self,
		"MapMetaData": MapMetaData.self,
		"OccupancyGrid": OccupancyGrid.self,
		"Odometry": Odometry.self,
		"Path": Path.self]
}