// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

public enum rosgraph_msgs {
    public static let all: [String: Message.Type] = [
        "Clock": Clock.self,
		"Log": Log.self,
		"TopicStatistics": TopicStatistics.self]
}