// Generated by msgbuilder 2024-02-26 03:36:01 +0000

import StdMsgs
import msgs

extension tf2_msgs {
	public enum FrameGraph: ServiceProt {
		public static let md5sum: String = "437ea58e9463815a0d511c7326b686b0"
		public static let datatype = "tf2_msgs/FrameGraph"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "d41d8cd98f00b204e9800998ecf8427e"
			public static let datatype = "tf2_msgs/FrameGraphRequest"
			public typealias ServiceType = FrameGraph
			public static let definition = ""
	
			public init() {
		
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "437ea58e9463815a0d511c7326b686b0"
			public static let datatype = "tf2_msgs/FrameGraphResponse"
			public typealias ServiceType = FrameGraph
			public static let definition = "string frame_yaml"
	
			public var frame_yaml: String
	
			public init(frame_yaml: String) {
				self.frame_yaml = frame_yaml
			}
	
			public init() {
				frame_yaml = String()
			}
		}

	}
}