// Generated by msgbuilder 2024-02-26 03:36:01 +0000

import StdMsgs

public enum tf2_msgs {
    public static let all: [String: Message.Type] = [
        "TF2Error": TF2Error.self,
		"TFMessage": TFMessage.self]
}