// Generated by msgbuilder 2024-02-26 03:36:01 +0000

import StdMsgs
import msgs

extension tf2_msgs {

	public struct TF2Error: Message {
		public static let md5sum: String = "4c42de037bbcef87ef90ec358299f5ac"
		public static let datatype = "tf2_msgs/TF2Error"
		public static let definition = """
			uint8 NO_ERROR = 0
			uint8 LOOKUP_ERROR = 1
			uint8 CONNECTIVITY_ERROR = 2
			uint8 EXTRAPOLATION_ERROR = 3
			uint8 INVALID_ARGUMENT_ERROR = 4
			uint8 TIMEOUT_ERROR = 5
			uint8 TRANSFORM_ERROR = 6
			uint8 error
			string error_string
			"""

		public static let NO_ERROR : UInt8 = 0
		public static let LOOKUP_ERROR : UInt8 = 1
		public static let CONNECTIVITY_ERROR : UInt8 = 2
		public static let EXTRAPOLATION_ERROR : UInt8 = 3
		public static let INVALID_ARGUMENT_ERROR : UInt8 = 4
		public static let TIMEOUT_ERROR : UInt8 = 5
		public static let TRANSFORM_ERROR : UInt8 = 6
		public var error: UInt8
		public var error_string: String

		public init(error: UInt8, error_string: String) {
			self.error = error
			self.error_string = error_string
		}

		public init() {
			error = UInt8()
			error_string = String()
		}
	}
}