// Generated by msgbuilder 2024-02-26 03:36:01 +0000

import StdMsgs
import msgs

extension tf2_msgs {

	public struct TFMessage: Message {
		public static let md5sum: String = "94810edda583a504dfda3829e70d7eec"
		public static let datatype = "tf2_msgs/TFMessage"
		public static let definition = """
			geometry_msgs/TransformStamped[] transforms
			"""

		public var transforms: [geometry_msgs.TransformStamped]

		public init(transforms: [geometry_msgs.TransformStamped]) {
			self.transforms = transforms
		}

		public init() {
			transforms = [geometry_msgs.TransformStamped]()
		}
	}
}