// Generated by msgbuilder 2024-03-05 04:36:15 +0000

import StdMsgs
import file_server
import msgs

extension  {
	public enum GetFiles: ServiceProt {
		public static let md5sum: String = "c3cdff040217d6fd73cddf99bcd1c960"
		public static let datatype = "/GetFiles"

	
		public struct Request: ServiceRequestMessage {
			public static let md5sum: String = "ae760accfe8bd01e78cec4edc336be00"
			public static let datatype = "/GetFilesRequest"
			public typealias ServiceType = GetFiles
			public static let definition = "string[] file_paths"
	
			public var file_paths: [string]
	
			public init(file_paths: [string]) {
				self.file_paths = file_paths
			}
	
			public init() {
				file_paths = [string]()
			}
		}

	
		public struct Response: ServiceResponseMessage {
			public static let md5sum: String = "10a280b0da6aeeecc9d2da337b711f26"
			public static let datatype = "/GetFilesResponse"
			public typealias ServiceType = GetFiles
			public static let definition = "file_server/File[] files"
	
			public var files: [file_server.File]
	
			public init(files: [file_server.File]) {
				self.files = files
			}
	
			public init() {
				files = [file_server.File]()
			}
		}

	}
}
