// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

public enum diagnostic_msgs {
    public static let all: [String: Message.Type] = [
        "DiagnosticArray": DiagnosticArray.self,
		"DiagnosticStatus": DiagnosticStatus.self,
		"KeyValue": KeyValue.self]
}