// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

public enum control_msgs {
    public static let all: [String: Message.Type] = [
        "AdmittanceControllerState": AdmittanceControllerState.self,
		"DynamicJointState": DynamicJointState.self,
		"GripperCommand": GripperCommand.self,
		"InterfaceValue": InterfaceValue.self,
		"JointComponentTolerance": JointComponentTolerance.self,
		"JointControllerState": JointControllerState.self,
		"JointJog": JointJog.self,
		"JointTolerance": JointTolerance.self,
		"JointTrajectoryControllerState": JointTrajectoryControllerState.self,
		"MecanumDriveControllerState": MecanumDriveControllerState.self,
		"MultiDOFCommand": MultiDOFCommand.self,
		"MultiDOFStateStamped": MultiDOFStateStamped.self,
		"PidState": PidState.self,
		"SingleDOFState": SingleDOFState.self,
		"SingleDOFStateStamped": SingleDOFStateStamped.self,
		"SteeringControllerStatus": SteeringControllerStatus.self]
}