// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension control_msgs {
	/// List of resource names, e.g. ["arm_joint_1", "arm_joint_2", "gripper_joint"]
	/// Key-value pairs representing interfaces and their corresponding values for each joint listed in `joint_names`
	public struct DynamicJointState: MessageWithHeader {
		public static let md5sum: String = "a63d907a59c439e6194d55a26a09d7bb"
		public static let datatype = "control_msgs/DynamicJointState"
		public static let definition = """
			std_msgs/Header header
			# List of resource names, e.g. ["arm_joint_1", "arm_joint_2", "gripper_joint"]
			string[] joint_names
			# Key-value pairs representing interfaces and their corresponding values for each joint listed in `joint_names`
			InterfaceValue[] interface_values
			"""

		public var header: std_msgs.Header
		public var joint_names: [String]
		public var interface_values: [InterfaceValue]

		public init(header: std_msgs.Header, joint_names: [String], interface_values: [InterfaceValue]) {
			self.header = header
			self.joint_names = joint_names
			self.interface_values = interface_values
		}

		public init() {
			header = std_msgs.Header()
			joint_names = [String]()
			interface_values = [InterfaceValue]()
		}
	}
}