// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension control_msgs {
	/// List of resource interface names
	/// Values corresponding to the list of interfaces in `interface_names`, [1.0, 0.0] for example
	public struct InterfaceValue: Message {
		public static let md5sum: String = "e601bb4a5c611343929051868c5b6142"
		public static let datatype = "control_msgs/InterfaceValue"
		public static let definition = """
			# List of resource interface names
			string[] interface_names
			# Values corresponding to the list of interfaces in `interface_names`, [1.0, 0.0] for example
			float64[] values
			"""

		public var interface_names: [String]
		public var values: [Float64]

		public init(interface_names: [String], values: [Float64]) {
			self.interface_names = interface_names
			self.values = values
		}

		public init() {
			interface_names = [String]()
			values = [Float64]()
		}
	}
}