// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension control_msgs {

	public struct MecanumDriveControllerState: MessageWithHeader {
		public static let md5sum: String = "03a68326514b0f752ed2e484a2bc29c3"
		public static let datatype = "control_msgs/MecanumDriveControllerState"
		public static let definition = """
			std_msgs/Header header
			float64 front_left_wheel_velocity
			float64 back_left_wheel_velocity
			float64 back_right_wheel_velocity
			float64 front_right_wheel_velocity
			geometry_msgs/Twist reference_velocity
			"""

		public var header: std_msgs.Header
		public var front_left_wheel_velocity: Float64
		public var back_left_wheel_velocity: Float64
		public var back_right_wheel_velocity: Float64
		public var front_right_wheel_velocity: Float64
		public var reference_velocity: geometry_msgs.Twist

		public init(header: std_msgs.Header, front_left_wheel_velocity: Float64, back_left_wheel_velocity: Float64, back_right_wheel_velocity: Float64, front_right_wheel_velocity: Float64, reference_velocity: geometry_msgs.Twist) {
			self.header = header
			self.front_left_wheel_velocity = front_left_wheel_velocity
			self.back_left_wheel_velocity = back_left_wheel_velocity
			self.back_right_wheel_velocity = back_right_wheel_velocity
			self.front_right_wheel_velocity = front_right_wheel_velocity
			self.reference_velocity = reference_velocity
		}

		public init() {
			header = std_msgs.Header()
			front_left_wheel_velocity = Float64()
			back_left_wheel_velocity = Float64()
			back_right_wheel_velocity = Float64()
			front_right_wheel_velocity = Float64()
			reference_velocity = geometry_msgs.Twist()
		}
	}
}