// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension control_msgs {
	/// This message presents current controller state of multiple degrees of freedom.
	/// Header timestamp should be update time of controller state
	public struct MultiDOFStateStamped: MessageWithHeader {
		public static let md5sum: String = "9dd85db40452573e39d1f1422edf7bfa"
		public static let datatype = "control_msgs/MultiDOFStateStamped"
		public static let definition = """
			# This message presents current controller state of multiple degrees of freedom.
			# Header timestamp should be update time of controller state
			std_msgs/Header header
			SingleDOFState[] dof_states
			"""

		public var header: std_msgs.Header
		public var dof_states: [SingleDOFState]

		public init(header: std_msgs.Header, dof_states: [SingleDOFState]) {
			self.header = header
			self.dof_states = dof_states
		}

		public init() {
			header = std_msgs.Header()
			dof_states = [SingleDOFState]()
		}
	}
}