// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension control_msgs {
	/// The message defines command for multiple degrees of freedom (DoF) typically used by many controllers.
	/// The message intentionally avoids 'joint' nomenclature because it can be generally use for command with
	/// different semantic meanings, e.g., joints, Cartesian axes, or have abstract meaning like GPIO interface.
	/// names of degrees of freedom
	/// values used by most of the controller
	/// First derivation of the values, e.g., velocity if values are positions.
	/// This is useful for PID and similar controllers.
	public struct MultiDOFCommand: Message {
		public static let md5sum: String = "c76bdae9e24fc824e306878081794062"
		public static let datatype = "control_msgs/MultiDOFCommand"
		public static let definition = """
			# The message defines command for multiple degrees of freedom (DoF) typically used by many controllers.
			# The message intentionally avoids 'joint' nomenclature because it can be generally use for command with
			# different semantic meanings, e.g., joints, Cartesian axes, or have abstract meaning like GPIO interface.
			# names of degrees of freedom
			string[] dof_names
			# values used by most of the controller
			float64[] values
			# First derivation of the values, e.g., velocity if values are positions.
			# This is useful for PID and similar controllers.
			float64[] values_dot
			"""

		public var dof_names: [String]
		public var values: [Float64]
		public var values_dot: [Float64]

		public init(dof_names: [String], values: [Float64], values_dot: [Float64]) {
			self.dof_names = dof_names
			self.values = values
			self.values_dot = values_dot
		}

		public init() {
			dof_names = [String]()
			values = [Float64]()
			values_dot = [Float64]()
		}
	}
}