// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension control_msgs {
	/// This message presents current controller state of one degree of freedom.
	/// DoF name, e.g., joint or Cartesian axis name
	/// The set point, that is, desired state.
	/// Current value of the process (ie: latest sensor measurement on the controlled value).
	/// First time-derivative of the process value. E.g., velocity.
	/// The error of the controlled value, essentially reference - feedback (for a regular PID implementation).
	/// First time-derivative of the error of the controlled value.
	/// Time between two consecutive updates/execution of the control law.
	/// Current output of the controller.
	public struct SingleDOFState: Message {
		public static let md5sum: String = "a02d3c3b4e5c408ab94cc420437f8501"
		public static let datatype = "control_msgs/SingleDOFState"
		public static let definition = """
			# This message presents current controller state of one degree of freedom.
			# DoF name, e.g., joint or Cartesian axis name
			string name
			# The set point, that is, desired state.
			float64 reference
			# Current value of the process (ie: latest sensor measurement on the controlled value).
			float64 feedback
			# First time-derivative of the process value. E.g., velocity.
			float64 feedback_dot
			# The error of the controlled value, essentially reference - feedback (for a regular PID implementation).
			float64 error
			# First time-derivative of the error of the controlled value.
			float64 error_dot
			# Time between two consecutive updates/execution of the control law.
			float64 time_step
			# Current output of the controller.
			float64 output
			"""

		public var name: String
		public var reference: Float64
		public var feedback: Float64
		public var feedback_dot: Float64
		public var error: Float64
		public var error_dot: Float64
		public var time_step: Float64
		public var output: Float64

		public init(name: String, reference: Float64, feedback: Float64, feedback_dot: Float64, error: Float64, error_dot: Float64, time_step: Float64, output: Float64) {
			self.name = name
			self.reference = reference
			self.feedback = feedback
			self.feedback_dot = feedback_dot
			self.error = error
			self.error_dot = error_dot
			self.time_step = time_step
			self.output = output
		}

		public init() {
			name = String()
			reference = Float64()
			feedback = Float64()
			feedback_dot = Float64()
			error = Float64()
			error_dot = Float64()
			time_step = Float64()
			output = Float64()
		}
	}
}