// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension control_msgs {
	/// This message presents current controller state of one degree of freedom.
	/// Header timestamp should be update time of controller state
	public struct SingleDOFStateStamped: MessageWithHeader {
		public static let md5sum: String = "d647a7fb21880b91cd214a8f392e4598"
		public static let datatype = "control_msgs/SingleDOFStateStamped"
		public static let definition = """
			# This message presents current controller state of one degree of freedom.
			# Header timestamp should be update time of controller state
			std_msgs/Header header
			SingleDOFState dof_state
			"""

		public var header: std_msgs.Header
		public var dof_state: SingleDOFState

		public init(header: std_msgs.Header, dof_state: SingleDOFState) {
			self.header = header
			self.dof_state = dof_state
		}

		public init() {
			header = std_msgs.Header()
			dof_state = SingleDOFState()
		}
	}
}