// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

extension control_msgs {

	public struct SteeringControllerStatus: MessageWithHeader {
		public static let md5sum: String = "fa0b44f6f68c7a7106e01f1c720f4015"
		public static let datatype = "control_msgs/SteeringControllerStatus"
		public static let definition = """
			std_msgs/Header header
			float64[] traction_wheels_position # positions of traction wheels if the robot is controlled by position
			float64[] traction_wheels_velocity # velocities of traction wheels if the robot is controlled by velocity
			float64[] steer_positions # positions of steering joints
			float64[] linear_velocity_command # value commanded to tractions joint
			float64[] steering_angle_command # values commanded to steering joints
			"""

		public var header: std_msgs.Header
		public var traction_wheels_position: [Float64]
		public var traction_wheels_velocity: [Float64]
		public var steer_positions: [Float64]
		public var linear_velocity_command: [Float64]
		public var steering_angle_command: [Float64]

		public init(header: std_msgs.Header, traction_wheels_position: [Float64], traction_wheels_velocity: [Float64], steer_positions: [Float64], linear_velocity_command: [Float64], steering_angle_command: [Float64]) {
			self.header = header
			self.traction_wheels_position = traction_wheels_position
			self.traction_wheels_velocity = traction_wheels_velocity
			self.steer_positions = steer_positions
			self.linear_velocity_command = linear_velocity_command
			self.steering_angle_command = steering_angle_command
		}

		public init() {
			header = std_msgs.Header()
			traction_wheels_position = [Float64]()
			traction_wheels_velocity = [Float64]()
			steer_positions = [Float64]()
			linear_velocity_command = [Float64]()
			steering_angle_command = [Float64]()
		}
	}
}