// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

public enum shape_msgs {
    public static let all: [String: Message.Type] = [
        "Mesh": Mesh.self,
		"MeshTriangle": MeshTriangle.self,
		"Plane": Plane.self,
		"SolidPrimitive": SolidPrimitive.self]
}