// Generated by msgbuilder 2024-02-23 05:14:48 +0000

import StdMsgs

public enum actionlib_msgs {
    public static let all: [String: Message.Type] = [
        "GoalID": GoalID.self,
		"GoalStatus": GoalStatus.self,
		"GoalStatusArray": GoalStatusArray.self]
}